SchemaVersion = 1
GeneratedAt = "2026-05-09T12:05:00Z"

[[Plugin]]
  Shortname = "hello"
  Shortdesc = "First plugin demo — prints a friendly greeting"
  Binary = "hint-hello"
  MagicCookieValue = "h1nt-hell0-c00k1e-2026"

  [[Plugin.Release]]
    Version = "0.1.2"
    OS = "darwin"
    Arch = "arm64"
    Sum = "be176e729c421f04b088caee6c571f90714756b9f35a7c3aa2e284717a92d6fd"

  [[Plugin.Release]]
    Version = "0.1.2"
    OS = "linux"
    Arch = "amd64"
    Sum = "22df807c7baf22b4cd40d4fe6a3519b68dfc8d33f9734a43d98bf935e4176193"

  [[Plugin.Command]]
    Name = "[your-name]"
    Desc = "Say hello to a custom name (default: world)"
