// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: internal/plugins/proto/hint_plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []string        `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Info *AdditionalInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_hint_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *RunCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunCommandRequest) GetInfo() *AdditionalInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type RunCommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_hint_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *RunCommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type AdditionalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TerminalState *IsTerminal         `protobuf:"bytes,1,opt,name=terminal_state,json=terminalState,proto3" json:"terminal_state,omitempty"`
	Dims          *TerminalDimensions `protobuf:"bytes,2,opt,name=dims,proto3" json:"dims,omitempty"`
	Env           map[string]string   `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AdditionalInfo) Reset() {
	*x = AdditionalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdditionalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalInfo) ProtoMessage() {}

func (x *AdditionalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalInfo.ProtoReflect.Descriptor instead.
func (*AdditionalInfo) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_hint_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *AdditionalInfo) GetTerminalState() *IsTerminal {
	if x != nil {
		return x.TerminalState
	}
	return nil
}

func (x *AdditionalInfo) GetDims() *TerminalDimensions {
	if x != nil {
		return x.Dims
	}
	return nil
}

func (x *AdditionalInfo) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type IsTerminal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdin  bool `protobuf:"varint,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Stdout bool `protobuf:"varint,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr bool `protobuf:"varint,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
}

func (x *IsTerminal) Reset() {
	*x = IsTerminal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsTerminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTerminal) ProtoMessage() {}

func (x *IsTerminal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTerminal.ProtoReflect.Descriptor instead.
func (*IsTerminal) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_hint_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *IsTerminal) GetStdin() bool {
	if x != nil {
		return x.Stdin
	}
	return false
}

func (x *IsTerminal) GetStdout() bool {
	if x != nil {
		return x.Stdout
	}
	return false
}

func (x *IsTerminal) GetStderr() bool {
	if x != nil {
		return x.Stderr
	}
	return false
}

type TerminalDimensions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  uint32 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *TerminalDimensions) Reset() {
	*x = TerminalDimensions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminalDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalDimensions) ProtoMessage() {}

func (x *TerminalDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_hint_plugin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalDimensions.ProtoReflect.Descriptor instead.
func (*TerminalDimensions) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_hint_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *TerminalDimensions) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TerminalDimensions) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_internal_plugins_proto_hint_plugin_proto protoreflect.FileDescriptor

var file_internal_plugins_proto_hint_plugin_proto_rawDesc = []byte{
	0x0a, 0x28, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x69, 0x6e, 0x74, 0x5f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x68, 0x69, 0x6e, 0x74,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x5b, 0x0a, 0x11, 0x52, 0x75,
	0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x12, 0x32, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x68, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x31, 0x0a, 0x12, 0x52, 0x75, 0x6e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xfe, 0x01, 0x0a, 0x0e, 0x41,
	0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x41, 0x0a,
	0x0e, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61,
	0x6c, 0x52, 0x0d, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x36, 0x0a, 0x04, 0x64, 0x69, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x68, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x04, 0x64, 0x69, 0x6d, 0x73, 0x12, 0x39, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x68, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03,
	0x65, 0x6e, 0x76, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x52, 0x0a, 0x0a, 0x49,
	0x73, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x64,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x22,
	0x42, 0x0a, 0x12, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x44, 0x69, 0x6d, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x32, 0x61, 0x0a, 0x0a, 0x48, 0x69, 0x6e, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x12, 0x53, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x21, 0x2e, 0x68, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x22, 0x2e, 0x68, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x69, 0x6e, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x2f, 0x63, 0x6c,
	0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_plugins_proto_hint_plugin_proto_rawDescOnce sync.Once
	file_internal_plugins_proto_hint_plugin_proto_rawDescData = file_internal_plugins_proto_hint_plugin_proto_rawDesc
)

func file_internal_plugins_proto_hint_plugin_proto_rawDescGZIP() []byte {
	file_internal_plugins_proto_hint_plugin_proto_rawDescOnce.Do(func() {
		file_internal_plugins_proto_hint_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_plugins_proto_hint_plugin_proto_rawDescData)
	})
	return file_internal_plugins_proto_hint_plugin_proto_rawDescData
}

var file_internal_plugins_proto_hint_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_plugins_proto_hint_plugin_proto_goTypes = []any{
	(*RunCommandRequest)(nil),  // 0: hint.plugin.v1.RunCommandRequest
	(*RunCommandResponse)(nil), // 1: hint.plugin.v1.RunCommandResponse
	(*AdditionalInfo)(nil),     // 2: hint.plugin.v1.AdditionalInfo
	(*IsTerminal)(nil),         // 3: hint.plugin.v1.IsTerminal
	(*TerminalDimensions)(nil), // 4: hint.plugin.v1.TerminalDimensions
	nil,                        // 5: hint.plugin.v1.AdditionalInfo.EnvEntry
}
var file_internal_plugins_proto_hint_plugin_proto_depIdxs = []int32{
	2, // 0: hint.plugin.v1.RunCommandRequest.info:type_name -> hint.plugin.v1.AdditionalInfo
	3, // 1: hint.plugin.v1.AdditionalInfo.terminal_state:type_name -> hint.plugin.v1.IsTerminal
	4, // 2: hint.plugin.v1.AdditionalInfo.dims:type_name -> hint.plugin.v1.TerminalDimensions
	5, // 3: hint.plugin.v1.AdditionalInfo.env:type_name -> hint.plugin.v1.AdditionalInfo.EnvEntry
	0, // 4: hint.plugin.v1.HintPlugin.RunCommand:input_type -> hint.plugin.v1.RunCommandRequest
	1, // 5: hint.plugin.v1.HintPlugin.RunCommand:output_type -> hint.plugin.v1.RunCommandResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_plugins_proto_hint_plugin_proto_init() }
func file_internal_plugins_proto_hint_plugin_proto_init() {
	if File_internal_plugins_proto_hint_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_plugins_proto_hint_plugin_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RunCommandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_plugins_proto_hint_plugin_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RunCommandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_plugins_proto_hint_plugin_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AdditionalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_plugins_proto_hint_plugin_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IsTerminal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_plugins_proto_hint_plugin_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TerminalDimensions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_plugins_proto_hint_plugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_plugins_proto_hint_plugin_proto_goTypes,
		DependencyIndexes: file_internal_plugins_proto_hint_plugin_proto_depIdxs,
		MessageInfos:      file_internal_plugins_proto_hint_plugin_proto_msgTypes,
	}.Build()
	File_internal_plugins_proto_hint_plugin_proto = out.File
	file_internal_plugins_proto_hint_plugin_proto_rawDesc = nil
	file_internal_plugins_proto_hint_plugin_proto_goTypes = nil
	file_internal_plugins_proto_hint_plugin_proto_depIdxs = nil
}
